spring.application.name=StudentManagement-Dev

spring.datasource.url=jdbc:postgresql://194.242.57.93:5437/student_db?options=-c%20timezone=UTC&sslmode=disable
spring.datasource.username=team6
spring.datasource.password=team644

#spring.datasource.url=jdbc:postgresql://194.242.57.93:5437/student_db?options=-c%20timezone=UTC&sslmode=disable
#spring.datasource.username=team6
#spring.datasource.password=team644

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.boot.admin.client.url=http://sb-admin:8080
spring.boot.admin.client.instance.service-url=http://student-m-team6-app:8080
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoints.web.exposure.include=*,health,info,loggers,logfile
logging.file.name=logs/team6.log
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daminigosavi1311@gmail.com
spring.mail.password=njla ccqz bsli vrlg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
